# 1. Load Data from all the stock csv files in directory

In [165]:
import datetime
import glob
import numpy as np
import pandas as pd

# Get CSV files list from a folder
csv_files = glob.glob("./TSLA-Stocks/TSLA16*.csv")

# Read each CSV file into DataFrame
# This creates a list of dataframes
df_list = (pd.read_csv(file) for file in csv_files)

# Concatenate all DataFrames
df   = pd.concat(df_list, ignore_index=True)

## 1.1 Drop duplicates & check for missing values

In [ ]:
dups = len(df['date'])-len(df['date'].drop_duplicates())
print("Before: # of duplicates", dups, ' out of ', len(df) , ' or ', round(dups/len(df),5), '%')

In [166]:
# Drop duplicate entries
df.drop_duplicates(subset=['date'], keep='first', inplace=True)

In [167]:
# verify there are no duplicate values
df["date"].is_unique
dups = len(df['date'])-len(df['date'].drop_duplicates())
print("After: # of duplicates", dups, ' out of ', len(df) , ' or ', round(dups/len(df),5), '%')

True

## 1.2 Print out all dates with confirming # of quotes (23400) and non-conforming number of quotes

In [168]:
df['date2_str']= df['date'][::].str.slice(stop=10)
pd_group_cnt = df.groupby(['date2_str'])['date2_str'].count().to_frame()
print("Confirming / correct number of quotes: 23,400")
print(pd_group_cnt.loc[pd_group_cnt['date2_str']==23400] )
pd.set_option('display.max_rows', None)
print("Dates Missing quotes")
print(pd_group_cnt.loc[pd_group_cnt['date2_str']!=23400] )
pd.set_option('display.max_rows', 10)
df = df.drop('date2_str', axis=1)

Confirming / correct number of quotes: 23,400
            date2_str
date2_str
2022-03-04      23400
2022-03-07      23400
2022-03-08      23400
2022-03-09      23400
2022-03-10      23400
...               ...
2022-10-03      23400
2022-10-04      23400
2022-10-05      23400
2022-10-06      23400
2022-10-07      23400

[151 rows x 1 columns]
Dates Missing quotes
            date2_str
date2_str
2022-03-03       5406

In [169]:
# Only want to track average to 3 decimal places.  Otherwise, end up with a lot of digits
df['average'] = df['average'].round(decimals = 3)

# 2.0 Describe data

In [170]:
df = df.sort_index(ascending=True)
#df = df.tail(10000)
#df = df.tail(30000)
df.describe()

,open,high,low,close,volume,average,barCount
count,3.538806e+06,3.538806e+06,3.538806e+06,3.538806e+06,3.538806e+06,3.538806e+06,3.538806e+06
mean,2.792378e+02,2.792584e+02,2.792166e+02,2.792375e+02,1.981523e+01,2.792374e+02,4.281384e+00
std,3.920246e+01,3.920186e+01,3.920304e+01,3.920243e+01,5.397667e+01,3.920246e+01,7.603019e+00
min,2.068667e+02,2.068733e+02,2.068567e+02,2.068733e+02,0.000000e+00,2.068680e+02,0.000000e+00
25%,2.444167e+02,2.444300e+02,2.443967e+02,2.444133e+02,1.000000e+00,2.444140e+02,1.000000e+00
50%,2.790100e+02,2.790300e+02,2.789967e+02,2.790100e+02,7.500000e+00,2.790095e+02,2.000000e+00
75%,3.031067e+02,3.031300e+02,3.030867e+02,3.031067e+02,2.331000e+01,3.031070e+02,5.000000e+00
max,3.841867e+02,3.842900e+02,3.840133e+02,3.841867e+02,3.025596e+04,3.842220e+02,3.700000e+02

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3538806 entries, 0 to 3612599
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   date       object
 1   open       float64
 2   high       float64
 3   low        float64
 4   close      float64
 5   volume     float64
 6   average    float64
 7   barCount   int64
 8   date2_str  object
dtypes: float64(6), int64(1), object(2)
memory usage: 270.0+ MB

# 3.0 Add computed columns

In [172]:
df.set_index('date')
df = df.sort_index()

In [173]:
# need this column to compute average of averages
df['_weighted_vol_avg'] = df['volume'] * df['average']

In [174]:
# lambda functions

#return 1st value in series
def firstValue(rows):
    return rows.iloc[0]

#return last value in series
def lastValue(rows):
    return rows.iloc[-1]

#return arrow indicator for boxed in values;
#   -1 below lower bound
#    0 inside the box
#   +1 above the max value
def arrow(new_amt, old_amt, box):
    if old_amt == np.nan:
        return np.nan
    if new_amt == np.nan:
        return np.nan
    if (new_amt - old_amt) <= (box * -1):
        return '-1'
    if (new_amt - old_amt) >= box:
        return '1'
    else:
        return '0'

#  lambda function to adds up the last 5 values, excluding the very last value
def sum_last_5(rows):
    #print ("[" , rows[-6:-1], rows[-6:-1].sum(), "]")
    return rows[-6:-1].sum()

#  lambda function returns lowest of the last 5 values, excluding the very last value
def min_last_5(rows):
    return rows.iloc[-6:-1].min()

#  lambda function returns higest of  the last 5 values, excluding the very last value
def max_last_5(rows):
    return rows.iloc[-6:-1].max()

# Store/Save 1 second windows for h1, h2, h3, h4, h5

In [175]:
%%time
df['h1s_high_max'] = df['high'].rolling(window=2).agg( {'maxLast': firstValue})
df['h1s_low_min'] = df['low'].rolling(window=2).agg( {'minLast': firstValue})
df['h1s_barCount_sum'] = df['barCount'].rolling(window=2).agg( {'sumLast': firstValue})
df['h1s_volume_sum'] = df['volume'].rolling(window=2).agg( {'sumLast': firstValue})
df['h1s_average_avg'] = df['average'].rolling(window=2).agg( {'sumLast': firstValue})

In [176]:
%%time
df['h2s_high_max'] = df['high'].rolling(window=3).agg( {'maxLast': firstValue})
df['h2s_low_min'] = df['low'].rolling(window=3).agg( {'minLast': firstValue})
df['h2s_barCount_sum'] = df['barCount'].rolling(window=3).agg( {'sumLast': firstValue})
df['h2s_volume_sum'] = df['volume'].rolling(window=3).agg( {'sumLast': firstValue})
df['h2s_average_avg'] = df['average'].rolling(window=3).agg( {'sumLast': firstValue})

In [177]:
%%time
df['h3s_high_max'] = df['high'].rolling(window=4).agg( {'maxLast': firstValue})
df['h3s_low_min'] = df['low'].rolling(window=4).agg( {'minLast': firstValue})
df['h3s_barCount_sum'] = df['barCount'].rolling(window=4).agg( {'sumLast': firstValue})
df['h3s_volume_sum'] = df['volume'].rolling(window=4).agg( {'sumLast': firstValue})
df['h3s_average_avg'] = df['average'].rolling(window=4).agg( {'sumLast': firstValue})

In [178]:
%%time
df['h4s_high_max'] = df['high'].rolling(window=5).agg( {'maxLast': firstValue})
df['h4s_low_min'] = df['low'].rolling(window=5).agg( {'minLast': firstValue})
df['h4s_barCount_sum'] = df['barCount'].rolling(window=5).agg( {'sumLast': firstValue})
df['h4s_volume_sum'] = df['volume'].rolling(window=5).agg( {'sumLast': firstValue})
df['h4s_average_avg'] = df['average'].rolling(window=5).agg( {'sumLast': firstValue})

## Compute 5 second window summary

In [179]:
%%time
df['h5s_high_max'] = df['high'].rolling(window=6).agg( {'maxLast5': max_last_5})
df['h5s_low_min'] = df['low'].rolling(window=6).agg( {'minLast5': min_last_5})
df['h5s_barCount_sum'] = df['barCount'].rolling(window=6).agg( {'sumLast5': sum_last_5})
df['h5s_volume_sum'] = df['volume'].rolling(window=6).agg( {'sumLast5': sum_last_5})
df['_h5s_weighted_vol_avg_sum'] = df['_weighted_vol_avg'].rolling(window=6).agg({'SumLast5': sum_last_5})

df['h5s_average_avg'] = df['_h5s_weighted_vol_avg_sum'] / df['h5s_volume_sum']
df['h5s_average_avg'] = df['h5s_average_avg'].round(decimals = 3)
df.drop(columns=['_h5s_weighted_vol_avg_sum'])
#

,date,open,high,low,close,volume,average,barCount,date2_str,_weighted_vol_avg,...,h4s_high_max,h4s_low_min,h4s_barCount_sum,h4s_volume_sum,h4s_average_avg,h5s_high_max,h5s_low_min,h5s_barCount_sum,h5s_volume_sum,h5s_average_avg
0,2022-03-11 15:29:54,265.1000,265.1000,265.0967,265.1000,0.00,265.100,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-03-11 15:29:55,265.0867,265.1200,265.0867,265.1100,12.00,265.101,4,2022-03-11,3181.21200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-03-11 15:29:56,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-03-11 15:29:57,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-03-11 15:29:58,265.0900,265.0900,265.0533,265.0533,12.36,265.069,4,2022-03-11,3276.25284,...,265.1000,265.0967,0.0,0.00,265.100,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3612595,2022-07-25 12:29:49,270.1367,270.1367,270.1333,270.1367,4.68,270.135,1,2022-07-25,1264.23180,...,270.0967,270.0967,0.0,0.00,270.097,270.2133,270.0833,5.0,51.00,270.152
3612596,2022-07-25 12:29:50,270.1367,270.1367,270.1333,270.1367,0.00,270.137,0,2022-07-25,0.00000,...,270.0967,270.0967,0.0,0.00,270.097,270.2133,270.0833,5.0,52.68,270.154
3612597,2022-07-25 12:29:51,270.1700,270.1700,270.1700,270.1700,3.00,270.170,1,2022-07-25,810.51000,...,270.2133,270.1767,2.0,12.00,270.205,270.2133,270.0833,5.0,52.68,270.154
3612598,2022-07-25 12:29:52,270.2100,270.2100,270.1533,270.1533,30.00,270.164,3,2022-07-25,8104.92000,...,270.1500,270.0833,2.0,36.00,270.139,270.2133,270.0833,6.0,55.68,270.155
3612599,2022-07-25 12:29:53,270.2100,270.2167,270.2100,270.2167,18.00,270.216,4,2022-07-25,4863.88800,...,270.1367,270.1333,1.0,4.68,270.135,270.2100,270.0833,7.0,73.68,270.150

## Compute 10 second window summary

In [180]:
%%time
df['h10s_high_max'] = df['high'].rolling(window=11).agg( {'maxLast5': max_last_5})
df['h10s_low_min'] = df['low'].rolling(window=11).agg( {'minLast5': min_last_5})
df['h10s_barCount_sum'] = df['barCount'].rolling(window=11).agg( {'sumLast5': sum_last_5})
df['h10s_volume_sum'] = df['volume'].rolling(window=11).agg( {'sumLast5': sum_last_5})
df['_h10s_weighted_vol_avg_sum'] = df['_weighted_vol_avg'].rolling(window=11).agg({'SumLast5': sum_last_5})

df['h10s_average_avg'] = df['_h10s_weighted_vol_avg_sum'] / df['h10s_volume_sum']
df['h10s_average_avg'] = df['h10s_average_avg'].round(decimals = 3)
df.drop(columns=['_h10s_weighted_vol_avg_sum'])

,date,open,high,low,close,volume,average,barCount,date2_str,_weighted_vol_avg,...,h5s_low_min,h5s_barCount_sum,h5s_volume_sum,_h5s_weighted_vol_avg_sum,h5s_average_avg,h10s_high_max,h10s_low_min,h10s_barCount_sum,h10s_volume_sum,h10s_average_avg
0,2022-03-11 15:29:54,265.1000,265.1000,265.0967,265.1000,0.00,265.100,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-03-11 15:29:55,265.0867,265.1200,265.0867,265.1100,12.00,265.101,4,2022-03-11,3181.21200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-03-11 15:29:56,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-03-11 15:29:57,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-03-11 15:29:58,265.0900,265.0900,265.0533,265.0533,12.36,265.069,4,2022-03-11,3276.25284,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3612595,2022-07-25 12:29:49,270.1367,270.1367,270.1333,270.1367,4.68,270.135,1,2022-07-25,1264.23180,...,270.0833,5.0,51.00,13777.7550,270.152,270.2133,270.0833,5.0,51.00,270.152
3612596,2022-07-25 12:29:50,270.1367,270.1367,270.1333,270.1367,0.00,270.137,0,2022-07-25,0.00000,...,270.0833,5.0,52.68,14231.6958,270.154,270.2133,270.0833,5.0,52.68,270.154
3612597,2022-07-25 12:29:51,270.1700,270.1700,270.1700,270.1700,3.00,270.170,1,2022-07-25,810.51000,...,270.0833,5.0,52.68,14231.6958,270.154,270.2133,270.0833,5.0,52.68,270.154
3612598,2022-07-25 12:29:52,270.2100,270.2100,270.1533,270.1533,30.00,270.164,3,2022-07-25,8104.92000,...,270.0833,6.0,55.68,15042.2058,270.155,270.2133,270.0833,6.0,55.68,270.155
3612599,2022-07-25 12:29:53,270.2100,270.2167,270.2100,270.2167,18.00,270.216,4,2022-07-25,4863.88800,...,270.0833,7.0,73.68,19904.6658,270.150,270.2100,270.0833,7.0,73.68,270.150

## Compute 15 second window summary

In [181]:
%%time
df['h15s_high_max'] = df['high'].rolling(window=16).agg( {'maxLast5': max_last_5})
df['h15s_low_min'] = df['low'].rolling(window=16).agg( {'minLast5': min_last_5})
df['h15s_barCount_sum'] = df['barCount'].rolling(window=16).agg( {'sumLast5': sum_last_5})
df['h15s_volume_sum'] = df['volume'].rolling(window=16).agg( {'sumLast5': sum_last_5})
df['_h15s_weighted_vol_avg_sum'] = df['_weighted_vol_avg'].rolling(window=16).agg({'SumLast5': sum_last_5})

df['h15s_average_avg'] = df['_h15s_weighted_vol_avg_sum'] / df['h15s_volume_sum']
df['h15s_average_avg'] = df['h15s_average_avg'].round(decimals = 3)
df.drop(columns=['_h15s_weighted_vol_avg_sum'])

,date,open,high,low,close,volume,average,barCount,date2_str,_weighted_vol_avg,...,h10s_low_min,h10s_barCount_sum,h10s_volume_sum,_h10s_weighted_vol_avg_sum,h10s_average_avg,h15s_high_max,h15s_low_min,h15s_barCount_sum,h15s_volume_sum,h15s_average_avg
0,2022-03-11 15:29:54,265.1000,265.1000,265.0967,265.1000,0.00,265.100,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-03-11 15:29:55,265.0867,265.1200,265.0867,265.1100,12.00,265.101,4,2022-03-11,3181.21200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-03-11 15:29:56,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-03-11 15:29:57,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,0.00000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-03-11 15:29:58,265.0900,265.0900,265.0533,265.0533,12.36,265.069,4,2022-03-11,3276.25284,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3612595,2022-07-25 12:29:49,270.1367,270.1367,270.1333,270.1367,4.68,270.135,1,2022-07-25,1264.23180,...,270.0833,5.0,51.00,13777.7550,270.152,270.2133,270.0833,5.0,51.00,270.152
3612596,2022-07-25 12:29:50,270.1367,270.1367,270.1333,270.1367,0.00,270.137,0,2022-07-25,0.00000,...,270.0833,5.0,52.68,14231.6958,270.154,270.2133,270.0833,5.0,52.68,270.154
3612597,2022-07-25 12:29:51,270.1700,270.1700,270.1700,270.1700,3.00,270.170,1,2022-07-25,810.51000,...,270.0833,5.0,52.68,14231.6958,270.154,270.2133,270.0833,5.0,52.68,270.154
3612598,2022-07-25 12:29:52,270.2100,270.2100,270.1533,270.1533,30.00,270.164,3,2022-07-25,8104.92000,...,270.0833,6.0,55.68,15042.2058,270.155,270.2133,270.0833,6.0,55.68,270.155
3612599,2022-07-25 12:29:53,270.2100,270.2167,270.2100,270.2167,18.00,270.216,4,2022-07-25,4863.88800,...,270.0833,7.0,73.68,19904.6658,270.150,270.2100,270.0833,7.0,73.68,270.150

In [182]:
df = df.drop(columns=['_weighted_vol_avg'])

In [183]:
df.set_index('date')
df = df.sort_index(ascending=False)
df.reset_index()
df.head(100)

,date,open,high,low,close,volume,average,barCount,date2_str,h1s_high_max,...,h10s_barCount_sum,h10s_volume_sum,_h10s_weighted_vol_avg_sum,h10s_average_avg,h15s_high_max,h15s_low_min,h15s_barCount_sum,h15s_volume_sum,_h15s_weighted_vol_avg_sum,h15s_average_avg
3612599,2022-07-25 12:29:53,270.2100,270.2167,270.2100,270.2167,18.00,270.216,4,2022-07-25,270.2100,...,7.0,73.68,19904.66580,270.150,270.2100,270.0833,7.0,73.68,19904.66580,270.150
3612598,2022-07-25 12:29:52,270.2100,270.2100,270.1533,270.1533,30.00,270.164,3,2022-07-25,270.1700,...,6.0,55.68,15042.20580,270.155,270.2133,270.0833,6.0,55.68,15042.20580,270.155
3612597,2022-07-25 12:29:51,270.1700,270.1700,270.1700,270.1700,3.00,270.170,1,2022-07-25,270.1367,...,5.0,52.68,14231.69580,270.154,270.2133,270.0833,5.0,52.68,14231.69580,270.154
3612596,2022-07-25 12:29:50,270.1367,270.1367,270.1333,270.1367,0.00,270.137,0,2022-07-25,270.1367,...,5.0,52.68,14231.69580,270.154,270.2133,270.0833,5.0,52.68,14231.69580,270.154
3612595,2022-07-25 12:29:49,270.1367,270.1367,270.1333,270.1367,4.68,270.135,1,2022-07-25,270.1500,...,5.0,51.00,13777.75500,270.152,270.2133,270.0833,5.0,51.00,13777.75500,270.152
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3612504,2022-07-25 12:28:18,269.9833,269.9833,269.9833,269.9833,3.00,269.983,1,2022-07-25,270.0100,...,10.0,54.51,14715.19578,269.954,270.0467,269.9067,10.0,54.51,14715.19578,269.954
3612503,2022-07-25 12:28:17,270.0100,270.0100,270.0067,270.0100,0.00,270.010,0,2022-07-25,270.0100,...,11.0,57.51,15525.32778,269.959,270.0467,269.9067,11.0,57.51,15525.32778,269.959
3612502,2022-07-25 12:28:16,270.0100,270.0100,270.0067,270.0100,0.00,270.010,0,2022-07-25,270.0100,...,11.0,57.51,15525.32778,269.959,270.0467,269.9067,11.0,57.51,15525.32778,269.959
3612501,2022-07-25 12:28:15,269.9433,270.0100,269.9400,270.0100,26.85,269.950,2,2022-07-25,270.0067,...,11.0,36.66,9897.63228,269.985,270.1133,269.9067,11.0,36.66,9897.63228,269.985
3612500,2022-07-25 12:28:14,270.0067,270.0067,269.9067,269.9067,27.66,269.958,8,2022-07-25,270.0467,...,7.0,33.00,8912.41800,270.073,270.1133,270.0400,7.0,33.00,8912.41800,270.073

## Compute Future 5 second window summary

In [184]:
df['f5s_average'] = df['average'].rolling(window=6).agg( {'firstValue': firstValue})
df.head(100)

,date,open,high,low,close,volume,average,barCount,date2_str,h1s_high_max,...,h10s_volume_sum,_h10s_weighted_vol_avg_sum,h10s_average_avg,h15s_high_max,h15s_low_min,h15s_barCount_sum,h15s_volume_sum,_h15s_weighted_vol_avg_sum,h15s_average_avg,f5s_average
3612599,2022-07-25 12:29:53,270.2100,270.2167,270.2100,270.2167,18.00,270.216,4,2022-07-25,270.2100,...,73.68,19904.66580,270.150,270.2100,270.0833,7.0,73.68,19904.66580,270.150,NaN
3612598,2022-07-25 12:29:52,270.2100,270.2100,270.1533,270.1533,30.00,270.164,3,2022-07-25,270.1700,...,55.68,15042.20580,270.155,270.2133,270.0833,6.0,55.68,15042.20580,270.155,NaN
3612597,2022-07-25 12:29:51,270.1700,270.1700,270.1700,270.1700,3.00,270.170,1,2022-07-25,270.1367,...,52.68,14231.69580,270.154,270.2133,270.0833,5.0,52.68,14231.69580,270.154,NaN
3612596,2022-07-25 12:29:50,270.1367,270.1367,270.1333,270.1367,0.00,270.137,0,2022-07-25,270.1367,...,52.68,14231.69580,270.154,270.2133,270.0833,5.0,52.68,14231.69580,270.154,NaN
3612595,2022-07-25 12:29:49,270.1367,270.1367,270.1333,270.1367,4.68,270.135,1,2022-07-25,270.1500,...,51.00,13777.75500,270.152,270.2133,270.0833,5.0,51.00,13777.75500,270.152,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3612504,2022-07-25 12:28:18,269.9833,269.9833,269.9833,269.9833,3.00,269.983,1,2022-07-25,270.0100,...,54.51,14715.19578,269.954,270.0467,269.9067,10.0,54.51,14715.19578,269.954,269.977
3612503,2022-07-25 12:28:17,270.0100,270.0100,270.0067,270.0100,0.00,270.010,0,2022-07-25,270.0100,...,57.51,15525.32778,269.959,270.0467,269.9067,11.0,57.51,15525.32778,269.959,269.941
3612502,2022-07-25 12:28:16,270.0100,270.0100,270.0067,270.0100,0.00,270.010,0,2022-07-25,270.0100,...,57.51,15525.32778,269.959,270.0467,269.9067,11.0,57.51,15525.32778,269.959,269.910
3612501,2022-07-25 12:28:15,269.9433,270.0100,269.9400,270.0100,26.85,269.950,2,2022-07-25,270.0067,...,36.66,9897.63228,269.985,270.1133,269.9067,11.0,36.66,9897.63228,269.985,269.964
3612500,2022-07-25 12:28:14,270.0067,270.0067,269.9067,269.9067,27.66,269.958,8,2022-07-25,270.0467,...,33.00,8912.41800,270.073,270.1133,270.0400,7.0,33.00,8912.41800,270.073,270.039

In [185]:
df = df.sort_index(ascending=True)
df.reset_index()
df.head(100)

,date,open,high,low,close,volume,average,barCount,date2_str,h1s_high_max,...,h10s_volume_sum,_h10s_weighted_vol_avg_sum,h10s_average_avg,h15s_high_max,h15s_low_min,h15s_barCount_sum,h15s_volume_sum,_h15s_weighted_vol_avg_sum,h15s_average_avg,f5s_average
0,2022-03-11 15:29:54,265.1000,265.1000,265.0967,265.1000,0.00,265.100,0,2022-03-11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,265.053
1,2022-03-11 15:29:55,265.0867,265.1200,265.0867,265.1100,12.00,265.101,4,2022-03-11,265.1000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,265.001
2,2022-03-11 15:29:56,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,265.1200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.952
3,2022-03-11 15:29:57,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,265.1100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.950
4,2022-03-11 15:29:58,265.0900,265.0900,265.0533,265.0533,12.36,265.069,4,2022-03-11,265.1100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2022-03-11 15:31:29,264.6867,264.6867,264.6833,264.6867,5.82,264.685,1,2022-03-11,264.7600,...,55.59,14714.04090,264.689,264.7667,264.6533,12.0,55.59,14714.04090,264.689,264.845
96,2022-03-11 15:31:30,264.7600,264.7600,264.7533,264.7533,24.12,264.759,4,2022-03-11,264.6867,...,58.11,15380.77650,264.684,264.7600,264.6533,12.0,58.11,15380.77650,264.684,264.900
97,2022-03-11 15:31:31,264.7533,264.7533,264.7533,264.7533,0.00,264.753,0,2022-03-11,264.7600,...,67.74,17931.81120,264.715,264.7600,264.6600,13.0,67.74,17931.81120,264.715,264.900
98,2022-03-11 15:31:32,264.8333,264.8333,264.6733,264.6733,9.00,264.780,2,2022-03-11,264.7533,...,58.77,15557.73924,264.722,264.7600,264.6600,12.0,58.77,15557.73924,264.722,264.900
99,2022-03-11 15:31:33,264.8600,264.8600,264.8600,264.8600,10.95,264.860,2,2022-03-11,264.8333,...,53.94,14280.48378,264.748,264.8333,264.6733,12.0,53.94,14280.48378,264.748,264.730

In [186]:
%%time
pd.set_option('display.max_rows', 100)

df['f5s_10c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.10), axis=1)
df['f5s_15c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.15), axis=1)
df['f5s_20c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.20), axis=1)
df['f5s_25c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.25), axis=1)
df['f5s_30c_arrow'] = df.apply(lambda x: arrow(x['f5s_average'], x['average'], 0.30), axis=1)

In [187]:
df.head(100)

,date,open,high,low,close,volume,average,barCount,date2_str,h1s_high_max,...,h15s_barCount_sum,h15s_volume_sum,_h15s_weighted_vol_avg_sum,h15s_average_avg,f5s_average,f5s_10c_arrow,f5s_15c_arrow,f5s_20c_arrow,f5s_25c_arrow,f5s_30c_arrow
0,2022-03-11 15:29:54,265.1000,265.1000,265.0967,265.1000,0.00,265.100,0,2022-03-11,NaN,...,NaN,NaN,NaN,NaN,265.053,0,0,0,0,0
1,2022-03-11 15:29:55,265.0867,265.1200,265.0867,265.1100,12.00,265.101,4,2022-03-11,265.1000,...,NaN,NaN,NaN,NaN,265.001,-1,0,0,0,0
2,2022-03-11 15:29:56,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,265.1200,...,NaN,NaN,NaN,NaN,264.952,-1,-1,0,0,0
3,2022-03-11 15:29:57,265.1100,265.1100,265.1100,265.1100,0.00,265.110,0,2022-03-11,265.1100,...,NaN,NaN,NaN,NaN,264.950,-1,-1,0,0,0
4,2022-03-11 15:29:58,265.0900,265.0900,265.0533,265.0533,12.36,265.069,4,2022-03-11,265.1100,...,NaN,NaN,NaN,NaN,264.976,0,0,0,0,0
5,2022-03-11 15:29:59,265.0533,265.0533,265.0533,265.0533,0.00,265.053,0,2022-03-11,265.0900,...,NaN,NaN,NaN,NaN,265.020,0,0,0,0,0
6,2022-03-11 15:30:00,265.0033,265.0300,264.9767,265.0300,335.13,265.001,65,2022-03-11,265.0533,...,NaN,NaN,NaN,NaN,265.020,0,0,0,0,0
7,2022-03-11 15:30:01,264.9467,264.9767,264.9333,264.9500,24.15,264.952,5,2022-03-11,265.0300,...,NaN,NaN,NaN,NaN,265.020,0,0,0,0,0
8,2022-03-11 15:30:02,264.9500,264.9500,264.9500,264.9500,0.00,264.950,0,2022-03-11,264.9767,...,NaN,NaN,NaN,NaN,264.977,0,0,0,0,0
9,2022-03-11 15:30:03,264.9433,265.0000,264.9433,265.0000,33.00,264.976,8,2022-03-11,264.9500,...,NaN,NaN,NaN,NaN,265.070,0,0,0,0,0
10,2022-03-11 15:30:04,265.0200,265.0200,265.0167,265.0200,3.00,265.020,1,2022-03-11,265.0000,...,NaN,NaN,NaN,NaN,265.100,0,0,0,0,0
11,2022-03-11 15:30:05,265.0200,265.0200,265.0200,265.0200,6.00,265.020,2,2022-03-11,265.0200,...,NaN,NaN,NaN,NaN,265.048,0,0,0,0,0
12,2022-03-11 15:30:06,265.0200,265.0200,265.0200,265.0200,0.00,265.020,0,2022-03-11,265.0200,...,NaN,NaN,NaN,NaN,264.990,0,0,0,0,0
13,2022-03-11 15:30:07,264.9767,264.9767,264.9767,264.9767,3.00,264.977,1,2022-03-11,265.0200,...,NaN,NaN,NaN,NaN,265.091,1,0,0,0,0
14,2022-03-11 15:30:08,265.0933,265.0933,265.0467,265.0467,12.00,265.070,3,2022-03-11,264.9767,...,NaN,NaN,NaN,NaN,265.090,0,0,0,0,0
15,2022-03-11 15:30:09,265.0500,265.1333,265.0500,265.1000,19.50,265.100,6,2022-03-11,265.0933,...,7.0,24.00,6360.95100,265.040,265.090,0,0,0,0,0
16,2022-03-11 15:30:10,265.0500,265.0500,265.0467,265.0467,6.00,265.048,2,2022-03-11,265.1333,...,12.0,40.50,10735.34100,265.070,265.090,0,0,0,0,0
17,2022-03-11 15:30:11,264.9900,264.9933,264.9900,264.9900,6.00,264.990,1,2022-03-11,265.0500,...,12.0,40.50,10735.50900,265.074,265.103,1,0,0,0,0
18,2022-03-11 15:30:12,265.0900,265.0933,265.0900,265.0900,3.00,265.091,1,2022-03-11,264.9933,...,13.0,46.50,12325.44900,265.063,265.035,0,0,0,0,0
19,2022-03-11 15:30:13,265.0900,265.0933,265.0900,265.0900,0.00,265.090,0,2022-03-11,265.0933,...,13.0,46.50,12325.79100,265.071,265.030,0,0,0,0,0
20,2022-03-11 15:30:14,265.0900,265.0933,265.0900,265.0900,0.00,265.090,0,2022-03-11,265.0933,...,10.0,34.50,9144.95100,265.071,265.053,0,0,0,0,0
21,2022-03-11 15:30:15,265.0900,265.0933,265.0900,265.0900,0.00,265.090,0,2022-03-11,265.0933,...,4.0,15.00,3975.50100,265.033,265.051,0,0,0,0,0
22,2022-03-11 15:30:16,265.1033,265.1033,265.1033,265.1033,3.00,265.103,1,2022-03-11,265.0933,...,2.0,9.00,2385.21300,265.024,265.020,0,0,0,0,0
23,2022-03-11 15:30:17,265.0767,265.0767,265.0300,265.0300,30.00,265.035,2,2022-03-11,265.1033,...,2.0,6.00,1590.58200,265.097,265.102,0,0,0,0,0
24,2022-03-11 15:30:18,265.0300,265.0333,265.0300,265.0300,0.00,265.030,0,2022-03-11,265.0767,...,3.0,33.00,8746.35900,265.041,265.110,0,0,0,0,0
25,2022-03-11 15:30:19,265.0533,265.0533,265.0533,265.0533,24.00,265.053,1,2022-03-11,265.0333,...,3.0,33.00,8746.35900,265.041,265.172,1,0,0,0,0
26,2022-03-11 15:30:20,265.0667,265.0667,265.0200,265.0200,9.00,265.051,3,2022-03-11,265.0533,...,4.0,57.00,15107.63100,265.046,265.167,1,0,0,0,0
27,2022-03-11 15:30:21,265.0200,265.0200,265.0200,265.0200,15.00,265.020,1,2022-03-11,265.0667,...,7.0,66.00,17493.09000,265.047,265.127,1,0,0,0,0
28,2022-03-11 15:30:22,265.1000,265.1100,265.0800,265.1100,30.00,265.102,4,2022-03-11,265.0200,...,7.0,78.00,20673.08100,265.040,265.127,0,0,0,0,0
29,2022-03-11 15:30:23,265.1100,265.1100,265.1067,265.1100,0.00,265.110,0,2022-03-11,265.1100,...,9.0,78.00,20675.09100,265.065,265.241,1,0,0,0,0
30,2022-03-11 15:30:24,265.1600,265.1833,265.1600,265.1833,6.00,265.172,2,2022-03-11,265.1100,...,9.0,78.00,20675.09100,265.065,265.211,0,0,0,0,0
31,2022-03-11 15:30:25,265.1667,265.1700,265.1667,265.1667,12.87,265.167,2,2022-03-11,265.1833,...,10.0,60.00,15904.85100,265.081,265.210,0,0,0,0,0
32,2022-03-11 15:30:26,265.1267,265.1267,265.1267,265.1267,3.00,265.127,1,2022-03-11,265.1700,...,9.0,63.87,16932.09129,265.102,265.210,0,0,0,0,0
33,2022-03-11 15:30:27,265.1267,265.1267,265.1267,265.1267,0.00,265.127,0,2022-03-11,265.1267,...,9.0,51.87,13752.17229,265.128,265.210,0,0,0,0,0
34,2022-03-11 15:30:28,265.2400,265.2533,265.2267,265.2533,9.00,265.241,3,2022-03-11,265.1267,...,5.0,21.87,5799.11229,265.163,265.206,0,0,0,0,0
35,2022-03-11 15:30:29,265.2067,265.2533,265.2000,265.2000,16.50,265.211,3,2022-03-11,265.2533,...,8.0,30.87,8186.28129,265.186,265.207,0,0,0,0,0
36,2022-03-11 15:30:30,265.2100,265.2100,265.2100,265.2100,3.00,265.210,1,2022-03-11,265.2533,...,9.0,41.37,10971.23079,265.198,265.129,0,0,0,0,0
37,2022-03-11 15:30:31,265.2100,265.2100,265.2100,265.2100,0.00,265.210,0,2022-03-11,265.2100,...,8.0,31.50,8354.16150,265.211,265.107,-1,0,0,0,0
38,2022-03-11 15:30:32,265.2100,265.2100,265.2100,265.2100,0.00,265.210,0,2022-03-11,265.2100,...,7.0,28.50,7558.78050,265.220,265.070,-1,0,0,0,0
39,2022-03-11 15:30:33,265.2233,265.2267,265.1867,265.1867,6.00,265.206,2,2022-03-11,265.2100,...,7.0,28.50,7558.78050,265.220,265.140,0,0,0,0,0
40,2022-03-11 15:30:34,265.2100,265.2100,265.1933,265.1933,18.00,265.207,2,2022-03-11,265.2267,...,6.0,25.50,6762.84750,265.210,265.131,0,0,0,0,0
41,2022-03-11 15:30:35,265.1000,265.1767,265.1000,265.1100,9.00,265.129,3,2022-03-11,265.2100,...,5.0,27.00,7160.59200,265.207,265.117,0,0,0,0,0
42,2022-03-11 15:30:36,265.1067,265.1067,265.1067,265.1067,6.00,265.107,2,2022-03-11,265.1767,...,7.0,33.00,8751.12300,265.186,265.117,0,0,0,0,0
43,2022-03-11 15:30:37,265.0700,265.0733,265.0700,265.0700,6.00,265.070,1,2022-03-11,265.1067,...,9.0,39.00,10341.76500,265.173,265.103,0,0,0,0,0
44,2022-03-11 15:30:38,265.1400,265.1400,265.1367,265.1400,3.00,265.140,1,2022-03-11,265.0733,...,10.0,45.00,11932.18500,265.160,265.043,0,0,0,0,0
45,2022-03-11 15:30:39,265.1667,265.1667,265.1167,265.1167,12.45,265.131,2,2022-03-11,265.1400,...,9.0,42.00,11136.36900,265.152,265.043,0,0,0,0,0
46,2022-03-11 15:30:40,265.1167,265.1167,265.1167,265.1167,0.00,265.117,0,2022-03-11,265.1667,...,9.0,36.45,9663.52395,265.117,265.043,0,0,0,0,0
47,2022-03-11 15:30:41,265.1167,265.1167,265.1167,265.1167,0.00,265.117,0,2022-03-11,265.1167,...,6.0,27.45,7277.36295,265.113,265.090,0,0,0,0,0
48,2022-03-11 15:30:42,265.0967,265.1100,265.0967,265.1100,20.31,265.103,4,2022-03-11,265.1167,...,4.0,21.45,5686.72095,265.115,265.088,0,0,0,0,0
49,2022-03-11 15:30:43,265.0433,265.0467,265.0433,265.0433,15.00,265.043,1,2022-03-11,265.1100,...,7.0,35.76,9480.54288,265.116,265.040,0,0,0,0,0
50,2022-03-11 15:30:44,265.0433,265.0467,265.0433,265.0433,0.00,265.043,0,2022-03-11,265.0467,...,7.0,47.76,12660.76788,265.091,265.008,0,0,0,0,0
51,2022-03-11 15:30:45,265.0433,265.0467,265.0433,265.0433,0.00,265.043,0,2022-03-11,265.0467,...,5.0,35.31,9359.88693,265.078,265.031,0,0,0,0,0
52,2022-03-11 15:30:46,265.0900,265.0900,265.0900,265.0900,30.00,265.090,1,2022-03-11,265.0467,...,5.0,35.31,9359.88693,265.078,265.067,0,0,0,0,0
53,2022-03-11 15:30:47,265.0867,265.0900,265.0867,265.0867,3.00,265.088,1,2022-03-11,265.0900,...,6.0,65.31,17312.58693,265.083,265.020,0,0,0,0,0
54,2022-03-11 15:30:48,265.0400,265.0400,265.0400,265.0400,39.12,265.040,5,2022-03-11,265.0900,...,3.0,48.00,12723.60900,265.075,265.020,0,0,0,0,0
55,2022-03-11 15:30:49,265.0067,265.0100,265.0067,265.0067,8.04,265.008,1,2022-03-11,265.0400,...,7.0,72.12,19116.32880,265.063,265.020,0,0,0,0,0
56,2022-03-11 15:30:50,265.0433,265.0433,265.0067,265.0067,9.00,265.031,2,2022-03-11,265.0100,...,8.0,80.16,21246.99312,265.057,265.003,0,0,0,0,0
57,2022-03-11 15:30:51,265.0667,265.0667,265.0667,265.0667,18.00,265.067,2,2022-03-11,265.0433,...,10.0,89.16,23632.27212,265.055,264.985,0,0,0,0,0
58,2022-03-11 15:30:52,265.0200,265.0200,265.0200,265.0200,3.00,265.020,1,2022-03-11,265.0667,...,11.0,77.16,20450.77812,265.044,264.987,0,0,0,0,0
59,2022-03-11 15:30:53,265.0200,265.0200,265.0200,265.0200,0.00,265.020,0,2022-03-11,265.0200,...,11.0,77.16,20450.57412,265.041,264.987,0,0,0,0,0
60,2022-03-11 15:30:54,265.0200,265.0200,265.0200,265.0200,0.00,265.020,0,2022-03-11,265.0200,...,6.0,38.04,10082.20932,265.042,264.973,0,0,0,0,0
61,2022-03-11 15:30:55,265.0067,265.0067,264.9967,264.9967,9.00,265.003,2,2022-03-11,265.0200,...,5.0,30.00,7951.54500,265.052,264.942,0,0,0,0,0
62,2022-03-11 15:30:56,264.9867,264.9867,264.9833,264.9867,3.00,264.985,1,2022-03-11,265.0067,...,5.0,30.00,7951.29300,265.043,264.950,0,0,0,0,0
63,2022-03-11 15:30:57,264.9867,264.9867,264.9833,264.9867,0.00,264.987,0,2022-03-11,264.9867,...,4.0,15.00,3975.04200,265.003,264.958,0,0,0,0,0
64,2022-03-11 15:30:58,264.9867,264.9867,264.9833,264.9867,0.00,264.987,0,2022-03-11,264.9867,...,3.0,12.00,3179.98200,264.998,264.940,0,0,0,0,0
65,2022-03-11 15:30:59,265.0100,265.0100,264.9533,264.9533,9.00,264.973,3,2022-03-11,264.9867,...,3.0,12.00,3179.98200,264.998,264.932,0,0,0,0,0
66,2022-03-11 15:31:00,264.9400,264.9500,264.9400,264.9500,12.45,264.942,4,2022-03-11,265.0100,...,6.0,21.00,5564.73900,264.988,264.910,0,0,0,0,0
67,2022-03-11 15:31:01,264.9500,264.9500,264.9500,264.9500,0.00,264.950,0,2022-03-11,264.9500,...,8.0,24.45,6478.23990,264.959,264.901,0,0,0,0,0
68,2022-03-11 15:31:02,264.9600,264.9600,264.9400,264.9400,48.00,264.958,3,2022-03-11,264.9500,...,7.0,21.45,5683.28490,264.955,264.836,-1,0,0,0,0
69,2022-03-11 15:31:03,264.9433,264.9433,264.9400,264.9400,28.92,264.940,7,2022-03-11,264.9600,...,10.0,69.45,18401.26890,264.957,264.751,-1,-1,0,0,0
70,2022-03-11 15:31:04,264.9400,264.9400,264.9233,264.9400,18.00,264.932,4,2022-03-11,264.9433,...,17.0,98.37,26063.33370,264.952,264.841,0,0,0,0,0
71,2022-03-11 15:31:05,264.9067,264.9200,264.8900,264.9200,27.00,264.910,4,2022-03-11,264.9400,...,18.0,107.37,28447.35270,264.947,264.853,0,0,0,0,0
72,2022-03-11 15:31:06,264.9000,264.9033,264.9000,264.9000,3.00,264.901,1,2022-03-11,264.9200,...,18.0,121.92,32301.39480,264.939,264.773,-1,0,0,0,0
73,2022-03-11 15:31:07,264.8900,264.8900,264.7800,264.7800,129.72,264.836,15,2022-03-11,264.9033,...,19.0,124.92,33096.09780,264.938,264.780,0,0,0,0,0
74,2022-03-11 15:31:08,264.7800,264.8000,264.7367,264.8000,48.90,264.751,8,2022-03-11,264.8900,...,31.0,206.64,54732.63972,264.870,264.820,0,0,0,0,0
75,2022-03-11 15:31:09,264.8167,264.8833,264.8167,264.8300,44.01,264.841,10,2022-03-11,264.8000,...,32.0,226.62,60016.89882,264.835,264.769,0,0,0,0,0
76,2022-03-11 15:31:10,264.8367,264.9100,264.8133,264.9100,99.00,264.853,14,2022-03-11,264.8833,...,38.0,252.63,66903.77523,264.829,264.809,0,0,0,0,0
77,2022-03-11 15:31:11,264.8133,264.8133,264.7367,264.7367,15.00,264.773,5,2022-03-11,264.9100,...,48.0,324.63,85971.65223,264.830,264.793,0,0,0,0,0
78,2022-03-11 15:31:12,264.7667,264.8833,264.7367,264.8833,44.94,264.780,11,2022-03-11,264.8133,...,52.0,336.63,89148.54423,264.826,264.834,0,0,0,0,0
79,2022-03-11 15:31:13,264.8200,264.8200,264.8200,264.8200,3.00,264.820,1,2022-03-11,264.8833,...,48.0,251.85,66693.23151,264.813,264.787,0,0,0,0,0
80,2022-03-11 15:31:14,264.7433,264.8167,264.7433,264.7900,48.00,264.769,15,2022-03-11,264.8200,...,41.0,205.95,54541.36761,264.828,264.787,0,0,0,0,0
81,2022-03-11 15:31:15,264.8433,264.8433,264.7867,264.7933,14.40,264.809,4,2022-03-11,264.8167,...,46.0,209.94,55594.62720,264.812,264.733,0,0,0,0,0
82,2022-03-11 15:31:16,264.7933,264.7967,264.7933,264.7933,0.00,264.793,0,2022-03-11,264.8433,...,36.0,125.34,33187.42980,264.779,264.746,0,0,0,0,0
83,2022-03-11 15:31:17,264.8367,264.8367,264.8333,264.8333,24.00,264.834,7,2022-03-11,264.7967,...,31.0,110.34,29215.83480,264.780,264.804,0,0,0,0,0
84,2022-03-11 15:31:18,264.7867,264.7867,264.7867,264.7867,3.00,264.787,1,2022-03-11,264.8367,...,27.0,89.40,23672.63760,264.795,264.683,-1,0,0,0,0
85,2022-03-11 15:31:19,264.7867,264.7867,264.7867,264.7867,0.00,264.787,0,2022-03-11,264.7867,...,27.0,89.40,23672.53860,264.793,264.767,0,0,0,0,0
86,2022-03-11 15:31:20,264.7333,264.7333,264.7333,264.7333,3.00,264.733,1,2022-03-11,264.7867,...,12.0,41.40,10963.62660,264.822,264.662,0,0,0,0,0
87,2022-03-11 15:31:21,264.7533,264.7567,264.7367,264.7367,6.00,264.746,2,2022-03-11,264.7333,...,9.0,30.00,7944.57600,264.819,264.668,0,0,0,0,0
88,2022-03-11 15:31:22,264.7900,264.8100,264.7900,264.8100,18.00,264.804,6,2022-03-11,264.7567,...,11.0,36.00,9533.05200,264.807,264.662,-1,0,0,0,0
89,2022-03-11 15:31:23,264.7033,264.7633,264.6300,264.6567,136.53,264.683,38,2022-03-11,264.8100,...,10.0,30.00,7943.50800,264.784,264.734,0,0,0,0,0
90,2022-03-11 15:31:24,264.7667,264.7667,264.7667,264.7667,3.30,264.767,1,2022-03-11,264.7633,...,47.0,163.53,43286.31699,264.700,264.685,0,0,0,0,0
91,2022-03-11 15:31:25,264.6933,264.6933,264.6533,264.6533,14.49,264.662,3,2022-03-11,264.7667,...,48.0,166.83,44160.04809,264.701,264.759,0,0,0,0,0
92,2022-03-11 15:31:26,264.6667,264.6700,264.6667,264.6667,8.97,264.668,1,2022-03-11,264.6933,...,50.0,178.32,47200.80147,264.697,264.753,0,0,0,0,0
93,2022-03-11 15:31:27,264.6633,264.6633,264.6600,264.6633,13.83,264.662,2,2022-03-11,264.6700,...,49.0,181.29,47986.39743,264.694,264.780,1,0,0,0,0
94,2022-03-11 15:31:28,264.7300,264.7600,264.7167,264.7600,15.00,264.734,5,2022-03-11,264.6633,...,45.0,177.12,46880.20089,264.680,264.860,1,0,0,0,0
95,2022-03-11 15:31:29,264.6867,264.6867,264.6833,264.6867,5.82,264.685,1,2022-03-11,264.7600,...,12.0,55.59,14714.04090,264.689,264.845,1,1,0,0,0
96,2022-03-11 15:31:30,264.7600,264.7600,264.7533,264.7533,24.12,264.759,4,2022-03-11,264.6867,...,12.0,58.11,15380.77650,264.684,264.900,1,0,0,0,0
97,2022-03-11 15:31:31,264.7533,264.7533,264.7533,264.7533,0.00,264.753,0,2022-03-11,264.7600,...,13.0,67.74,17931.81120,264.715,264.900,1,0,0,0,0
98,2022-03-11 15:31:32,264.8333,264.8333,264.6733,264.6733,9.00,264.780,2,2022-03-11,264.7533,...,12.0,58.77,15557.73924,264.722,264.900,1,0,0,0,0
99,2022-03-11 15:31:33,264.8600,264.8600,264.8600,264.8600,10.95,264.860,2,2022-03-11,264.8333,...,12.0,53.94,14280.48378,264.748,264.730,-1,0,0,0,0

In [188]:
%%time
df.to_csv("./TSLA-Stocks/ALL.csv", index=False)